package lab6p2_haroldcamas;

import java.awt.Dialog;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author harol
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dl_opcionesPortatil = new javax.swing.JDialog();
        jLabel7 = new javax.swing.JLabel();
        cb_tamaño = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        sp_duracion = new javax.swing.JSpinner();
        jLabel9 = new javax.swing.JLabel();
        cb_estuche = new javax.swing.JComboBox<>();
        bt_agregarPortatil = new javax.swing.JButton();
        dl_opcionesEstacionaria = new javax.swing.JDialog();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        sp_almacenamiento = new javax.swing.JSpinner();
        jLabel12 = new javax.swing.JLabel();
        sp_controles = new javax.swing.JSpinner();
        tf_conexion = new javax.swing.JTextField();
        bt_agregarEstacionaria = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tf_identificacion = new javax.swing.JTextField();
        tf_fabricante = new javax.swing.JTextField();
        sp_años = new javax.swing.JSpinner();
        sp_precio = new javax.swing.JSpinner();
        tf_modelo = new javax.swing.JTextField();
        cb_tipo = new javax.swing.JComboBox<>();
        bt_agregarConsola = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_tabla = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jl_juegos = new javax.swing.JList<>();

        jLabel7.setText("Tamaño");

        cb_tamaño.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pequeña", "Mediana", "Grande" }));

        jLabel8.setText("Duracion");

        jLabel9.setText("Estuche");

        cb_estuche.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Con Estuche", "Sin Estuche" }));

        bt_agregarPortatil.setText("Agregar");
        bt_agregarPortatil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_agregarPortatilMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout dl_opcionesPortatilLayout = new javax.swing.GroupLayout(dl_opcionesPortatil.getContentPane());
        dl_opcionesPortatil.getContentPane().setLayout(dl_opcionesPortatilLayout);
        dl_opcionesPortatilLayout.setHorizontalGroup(
            dl_opcionesPortatilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dl_opcionesPortatilLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(dl_opcionesPortatilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(dl_opcionesPortatilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dl_opcionesPortatilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(cb_tamaño, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(sp_duracion))
                    .addComponent(cb_estuche, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34))
            .addGroup(dl_opcionesPortatilLayout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(bt_agregarPortatil)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        dl_opcionesPortatilLayout.setVerticalGroup(
            dl_opcionesPortatilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dl_opcionesPortatilLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(dl_opcionesPortatilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cb_tamaño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(dl_opcionesPortatilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(sp_duracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(dl_opcionesPortatilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(cb_estuche, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(bt_agregarPortatil)
                .addGap(29, 29, 29))
        );

        jLabel10.setText("Controles");

        jLabel11.setText("Almacenamiento");

        jLabel12.setText("Conexion");

        bt_agregarEstacionaria.setText("Agregar");
        bt_agregarEstacionaria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_agregarEstacionariaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout dl_opcionesEstacionariaLayout = new javax.swing.GroupLayout(dl_opcionesEstacionaria.getContentPane());
        dl_opcionesEstacionaria.getContentPane().setLayout(dl_opcionesEstacionariaLayout);
        dl_opcionesEstacionariaLayout.setHorizontalGroup(
            dl_opcionesEstacionariaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dl_opcionesEstacionariaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dl_opcionesEstacionariaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel12)
                    .addComponent(jLabel11)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(dl_opcionesEstacionariaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(sp_almacenamiento, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
                    .addComponent(sp_controles, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tf_conexion))
                .addGap(34, 34, 34))
            .addGroup(dl_opcionesEstacionariaLayout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(bt_agregarEstacionaria)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        dl_opcionesEstacionariaLayout.setVerticalGroup(
            dl_opcionesEstacionariaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dl_opcionesEstacionariaLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(dl_opcionesEstacionariaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(sp_controles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(dl_opcionesEstacionariaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(sp_almacenamiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(dl_opcionesEstacionariaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(tf_conexion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(bt_agregarEstacionaria)
                .addGap(32, 32, 32))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        jLabel1.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("PolyStation Games");
        jLabel1.setAlignmentX(0.5F);
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Identificacion");

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Fabricante");

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Años de Uso");

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Precio");

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Modelo");

        cb_tipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Portatil", "Estacionaria" }));

        bt_agregarConsola.setText("Agregar Consola");
        bt_agregarConsola.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_agregarConsolaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(242, 242, 242)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addGap(61, 61, 61)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tf_identificacion)
                    .addComponent(tf_fabricante)
                    .addComponent(sp_años)
                    .addComponent(sp_precio)
                    .addComponent(tf_modelo, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 83, Short.MAX_VALUE)
                .addComponent(cb_tipo, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(146, 146, 146))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bt_agregarConsola, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(216, 216, 216))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tf_identificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb_tipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(tf_fabricante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(sp_años, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(sp_precio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(tf_modelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addComponent(bt_agregarConsola)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));

        tb_tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Identificacion", "Fabricante", "Uso", "Precio", "Modelo", "Tipo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tb_tabla);

        jl_juegos.setModel(new DefaultListModel());
        jScrollPane2.setViewportView(jl_juegos);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(jScrollPane2))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_agregarConsolaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_agregarConsolaMouseClicked
        if(tf_identificacion.getText().equals("") || tf_fabricante.getText().equals("") || (int) sp_duracion.getModel().getValue() < 0 || (int) sp_precio.getModel().getValue() <= 0 || tf_modelo.getText().equals("") || cb_tipo.getSelectedIndex() == -1){
            JOptionPane.showMessageDialog(this, "Tiene que llenar bien todos los datos!");
        }
        else{
            if(cb_tipo.getSelectedIndex() == 0){
                dl_opcionesPortatil.pack();
                dl_opcionesPortatil.setModal(true);
                dl_opcionesPortatil.setLocationRelativeTo(this);
                dl_opcionesPortatil.setVisible(true);
                dl_opcionesPortatil.setAlwaysOnTop(true); 
            }
            else{
                dl_opcionesEstacionaria.pack();
                dl_opcionesEstacionaria.setModal(true);
                dl_opcionesEstacionaria.setLocationRelativeTo(this);
                dl_opcionesEstacionaria.setVisible(true);
                dl_opcionesEstacionaria.setAlwaysOnTop(true); 
            }
        }
    }//GEN-LAST:event_bt_agregarConsolaMouseClicked

    private void bt_agregarPortatilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_agregarPortatilMouseClicked
        if(cb_tamaño.getSelectedIndex() == -1 || cb_estuche.getSelectedIndex() == -1 || (int) sp_duracion.getModel().getValue() <= 0){
            JOptionPane.showMessageDialog(dl_opcionesPortatil, "Tiene que llenar las casillas!");
        }
        else{
            boolean estuche = true;
            if(cb_estuche.getSelectedIndex() == 0){
                estuche = true;
            }
            else{
                estuche = false;
            }
            Consola c = new Portatil((String) cb_tamaño.getSelectedItem(), 
                    (int) sp_duracion.getModel().getValue(), estuche, tf_identificacion.getText(), tf_fabricante.getText(),
                    (int) sp_años.getModel().getValue(), (int) sp_precio.getModel().getValue(), tf_modelo.getText());
            consolas.add(c);
            
            tf_identificacion.setText("");
            tf_fabricante.setText("");
            sp_años.getModel().setValue(0);
            sp_precio.getModel().setValue(0);
            tf_modelo.setText("");
            cb_tamaño.setSelectedIndex(-1);
            cb_estuche.setSelectedIndex(-1);
            sp_duracion.getModel().setValue(0);
            JOptionPane.showMessageDialog(dl_opcionesPortatil, "Agregado exitosamente!");
            dl_opcionesPortatil.setVisible(false);
        }
    }//GEN-LAST:event_bt_agregarPortatilMouseClicked

    private void bt_agregarEstacionariaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_agregarEstacionariaMouseClicked
        if((int)sp_controles.getModel().getValue() == 0 || (int) sp_almacenamiento.getModel().getValue() == 0 || tf_conexion.getText().equals("")){
            JOptionPane.showMessageDialog(dl_opcionesEstacionaria, "Tiene que llenar las casillas!");
        }
        else{
            Consola c = new Estacionaria((int)sp_controles.getModel().getValue(),(int) sp_almacenamiento.getModel().getValue(),tf_conexion.getText(),
            tf_identificacion.getText(), tf_fabricante.getText(),
            (int) sp_años.getModel().getValue(), (int) sp_precio.getModel().getValue(), tf_modelo.getText());
            consolas.add(c);
            
            tf_identificacion.setText("");
            tf_fabricante.setText("");
            sp_años.getModel().setValue(0);
            sp_precio.getModel().setValue(0);
            tf_modelo.setText("");
            sp_controles.getModel().setValue(0);
            sp_almacenamiento.getModel().setValue(0);
            tf_conexion.setText("");
            JOptionPane.showMessageDialog(dl_opcionesEstacionaria, "Agregado exitosamente!");
            dl_opcionesEstacionaria.setVisible(false);
        }
    }//GEN-LAST:event_bt_agregarEstacionariaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }
    
    ArrayList<Juego> juegos = new ArrayList();
    ArrayList<Consola> consolas = new ArrayList();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_agregarConsola;
    private javax.swing.JButton bt_agregarEstacionaria;
    private javax.swing.JButton bt_agregarPortatil;
    private javax.swing.JComboBox<String> cb_estuche;
    private javax.swing.JComboBox<String> cb_tamaño;
    private javax.swing.JComboBox<String> cb_tipo;
    private javax.swing.JDialog dl_opcionesEstacionaria;
    private javax.swing.JDialog dl_opcionesPortatil;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> jl_juegos;
    private javax.swing.JSpinner sp_almacenamiento;
    private javax.swing.JSpinner sp_años;
    private javax.swing.JSpinner sp_controles;
    private javax.swing.JSpinner sp_duracion;
    private javax.swing.JSpinner sp_precio;
    private javax.swing.JTable tb_tabla;
    private javax.swing.JTextField tf_conexion;
    private javax.swing.JTextField tf_fabricante;
    private javax.swing.JTextField tf_identificacion;
    private javax.swing.JTextField tf_modelo;
    // End of variables declaration//GEN-END:variables
}
